### ISSUE TITLE
Not an issue - Halite gifs

### ISSUE THREAD

**Issue by Edouard360** [Edouard360/Halite-Python-RL#1]
![halite](https://user-images.githubusercontent.com/15527397/30818756-c0526c06-a21c-11e7-95a8-317dded1e761.gif)

**Comment by Edouard360** [comment]
<img width="440" alt="strength illustration" src="https://user-images.githubusercontent.com/15527397/30821143-9bec343e-a224-11e7-8087-2463d4489475.png">
<img width="440" alt="strength illustration also has a strength" src="https://user-images.githubusercontent.com/15527397/30821163-b0d70cf2-a224-11e7-9fbc-e1ff483f53b8.png">
<img width="444" alt="attack" src="https://user-images.githubusercontent.com/15527397/30821191-c79c6b30-a224-11e7-9ec3-0a9314f2d12d.png">
<img width="440" alt="prod illustration -" src="https://user-images.githubusercontent.com/15527397/30821225-dcadd946-a224-11e7-829c-5d3b700c008c.png">

**Comment by Edouard360** [comment]
![conquermap](https://user-images.githubusercontent.com/15527397/30869334-20c1a650-a2e1-11e7-9c1b-9233640ccd01.gif)
<img width="497" alt="the strength map" src="https://user-images.githubusercontent.com/15527397/30869344-24b55702-a2e1-11e7-9383-0dc7f562e5d6.png">
![remainingstill](https://user-images.githubusercontent.com/15527397/30869349-27abe944-a2e1-11e7-8b6e-94dfde9e15a1.gif)
<img width="494" alt="production map" src="https://user-images.githubusercontent.com/15527397/30869351-299bd8c2-a2e1-11e7-80d2-62699551aaa2.png">
![complementary production](https://user-images.githubusercontent.com/15527397/30869356-2bce1fce-a2e1-11e7-86e6-339335636e0e.gif)
![invariant porduction](https://user-images.githubusercontent.com/15527397/30869359-2e235f3c-a2e1-11e7-87ce-109ea5c08c27.gif)
<img width="495" alt="matrix" src="https://user-images.githubusercontent.com/15527397/30869363-30c46a56-a2e1-11e7-8882-1c22bc2256f8.png">
![matrix to send](https://user-images.githubusercontent.com/15527397/30869368-32e9be94-a2e1-11e7-831e-3d74b19981a4.gif)
![rewardproduction](https://user-images.githubusercontent.com/15527397/30869372-363a5c7a-a2e1-11e7-8784-9a83d4c62c44.gif)
<img width="536" alt="screen shot 2017-09-26 at 17 34 04" src="https://user-images.githubusercontent.com/15527397/30869383-3e046b94-a2e1-11e7-91c7-ecf2381eb83f.png">
![untrainedbot](https://user-images.githubusercontent.com/15527397/30869385-3fd296e4-a2e1-11e7-81f7-3a9436740792.gif)
![improvedbot](https://user-images.githubusercontent.com/15527397/30869390-41fe0d22-a2e1-11e7-9205-88fd2c47a544.gif)

**Comment by lremus** [comment]
Haha nice trick !

**Comment by Edouard360** [comment]
![1](https://user-images.githubusercontent.com/15527397/31232356-f48483b8-a9e9-11e7-8c6a-34b63bcab417.gif)
![2](https://user-images.githubusercontent.com/15527397/31232357-f7ccef06-a9e9-11e7-96fa-286ad9e22aad.gif)
![3](https://user-images.githubusercontent.com/15527397/31232360-fa4bbac8-a9e9-11e7-8104-19bd49f43b2f.gif)
![4](https://user-images.githubusercontent.com/15527397/31232362-fc674822-a9e9-11e7-958f-db34cfafc625.gif)
![5](https://user-images.githubusercontent.com/15527397/31232371-fe85eaf0-a9e9-11e7-97d7-dc96a15a7e92.gif)
![6](https://user-images.githubusercontent.com/15527397/31232374-00d8f252-a9ea-11e7-82f3-505eb6556029.gif)

**Comment by Edouard360** [comment]
<img width="633" alt="performance" src="https://user-images.githubusercontent.com/15527397/31232668-db0cf324-a9ea-11e7-8f9e-923c582df6e8.png">

**Comment by Edouard360** [comment]
![reward5-bis](https://user-images.githubusercontent.com/15527397/31237062-2b3ab4fc-a9f6-11e7-88c9-d0f39e6c9bf6.gif)
![reward4](https://user-images.githubusercontent.com/15527397/31237063-2b683ce2-a9f6-11e7-9656-3de7e6c743f7.gif)
![reward5](https://user-images.githubusercontent.com/15527397/31237070-2be72b1a-a9f6-11e7-8964-d352e99a6628.gif)
![reward1-bis](https://user-images.githubusercontent.com/15527397/31237066-2b7e737c-a9f6-11e7-95d6-47daee50e051.gif)
![reward1](https://user-images.githubusercontent.com/15527397/31237067-2b81fb78-a9f6-11e7-8f31-12141c2dba7a.gif)
![reward2](https://user-images.githubusercontent.com/15527397/31237065-2b6ebc48-a9f6-11e7-8325-39a00c15c138.gif)
![reward3](https://user-images.githubusercontent.com/15527397/31237064-2b6dfe0c-a9f6-11e7-8df7-1827b673a778.gif)
![reward4-bis](https://user-images.githubusercontent.com/15527397/31237068-2b8448f6-a9f6-11e7-8b71-5c54264e7146.gif)

**Comment by Edouard360** [comment]
![optimal behaviour](https://user-images.githubusercontent.com/15527397/33241911-e22a4b74-d2cc-11e7-9a31-d89129b1248a.gif)
![proba-long](https://user-images.githubusercontent.com/15527397/33241913-e8c55514-d2cc-11e7-808c-0b89fbb9d547.gif)
![dijkstra-expansion](https://user-images.githubusercontent.com/15527397/33241925-fc114948-d2cc-11e7-8c39-fed8064a466f.gif)
![dijkstra](https://user-images.githubusercontent.com/15527397/33241930-1388cd26-d2cd-11e7-87a8-d775c81efc01.gif)

**Comment by Edouard360** [comment]
![mnist_inverted](https://user-images.githubusercontent.com/15527397/33954784-bbf6379a-e039-11e7-8050-2a0fb9aac62a.png)
![mnist_normal](https://user-images.githubusercontent.com/15527397/33954785-bc2283cc-e039-11e7-8bb8-d75cdeec5de1.png)

**Comment by Edouard360** [comment]
![mnist_normal1](https://user-images.githubusercontent.com/15527397/33955346-7ab222ba-e03b-11e7-98d5-ccd9a3f793bc.png)
![mnist_inverted1](https://user-images.githubusercontent.com/15527397/33955345-7a993958-e03b-11e7-920b-8a59103b4206.png)

**Comment by Edouard360** [comment]
![amazing_success_1](https://user-images.githubusercontent.com/15527397/34457805-d84692a6-edbc-11e7-9ffb-a3ff044c2964.png)
![slightly mistaken](https://user-images.githubusercontent.com/15527397/34457806-e5bcc9be-edbc-11e7-8eab-25dae8f00b27.png)
![attention1](https://user-images.githubusercontent.com/15527397/34457808-fdd7c1c0-edbc-11e7-90f9-d10ab395ca7a.gif)
